# Generated by Django 2.1.7 on 2019-02-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('投手', '投手'), ('捕手', '捕手'), ('内野手', '内野手'), ('外野手', '外野手')], max_length=255)),
                ('born', models.DateField(null=True)),
                ('age', models.IntegerField(default=0)),
                ('years', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('blood', models.CharField(max_length=255)),
                ('pi_pa', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
