# Generated by Django 2.1.7 on 2019-05-25 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_player_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('stadium', models.CharField(max_length=255)),
                ('vs', models.CharField(max_length=255)),
                ('result_score', models.CharField(max_length=255)),
                ('win_lose', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('avg', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('at_bat', models.IntegerField(default=0)),
                ('hit', models.IntegerField(default=0)),
                ('hr', models.IntegerField(default=0)),
                ('rbi', models.IntegerField(default=0)),
                ('bb_hbp', models.IntegerField(default=0)),
                ('stolen_bases', models.IntegerField(default=0)),
                ('sacrifice_bunts', models.IntegerField(default=0)),
                ('sacrifice_flies', models.IntegerField(default=0)),
                ('strike_outs', models.IntegerField(default=0)),
                ('innings', models.IntegerField(default=0)),
                ('middle_score', models.CharField(max_length=255)),
                ('difference', models.CharField(max_length=255)),
                ('out_count', models.IntegerField(default=0)),
                ('first_runner', models.CharField(max_length=255)),
                ('second_runner', models.CharField(max_length=255)),
                ('third_runner', models.CharField(max_length=255)),
                ('ball_count', models.IntegerField(default=0)),
                ('strike_count', models.IntegerField(default=0)),
                ('result', models.CharField(max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball_player_app.Player')),
            ],
            options={
                'db_table': 'player_result',
            },
        ),
    ]
