# Generated by Django 2.1.7 on 2019-05-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_player_app', '0002_playerresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerresult',
            name='ball_count',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='innings',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='out_count',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='strike_count',
            field=models.CharField(max_length=255),
        ),
    ]
