# Generated by Django 2.2.2 on 2019-06-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_player_app', '0003_auto_20190525_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='info_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default='', max_length=255),
        ),
    ]
