# Generated by Django 2.2.2 on 2019-07-12 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_player_app', '0004_auto_20190622_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='no',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PlayerBattingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('avg', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('game', models.IntegerField(default=0)),
                ('plate_appearances', models.IntegerField(default=0)),
                ('at_bats', models.IntegerField(default=0)),
                ('runs_scored', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('two_base_hits', models.IntegerField(default=0)),
                ('three_base_hits', models.IntegerField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
                ('total_bases', models.IntegerField(default=0)),
                ('runs_batted_in', models.IntegerField(default=0)),
                ('stolen_bases', models.IntegerField(default=0)),
                ('caught_stealing', models.IntegerField(default=0)),
                ('sacrifice_bunts', models.IntegerField(default=0)),
                ('sacrifice_flies', models.IntegerField(default=0)),
                ('bases_on_balls', models.IntegerField(default=0)),
                ('intentional_walk', models.IntegerField(default=0)),
                ('hit_by_pitch', models.IntegerField(default=0)),
                ('strike_outs', models.IntegerField(default=0)),
                ('double_plays', models.IntegerField(default=0)),
                ('on_base_percentage', models.IntegerField(default=0)),
                ('slugging_percentage', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball_player_app.Player')),
            ],
            options={
                'db_table': 'player_batting_stats',
            },
        ),
    ]
