# Generated by Django 2.2.2 on 2019-07-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_player_app', '0005_auto_20190712_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbattingstats',
            name='on_base_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='playerbattingstats',
            name='slugging_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
