# Generated by Django 2.2.4 on 2019-08-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_player_app', '0006_auto_20190712_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPitchingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('earned_run_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('game', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('holds', models.IntegerField(default=0)),
                ('hold_points', models.IntegerField(default=0)),
                ('complete_games', models.IntegerField(default=0)),
                ('shoutout', models.IntegerField(default=0)),
                ('no_walks', models.IntegerField(default=0)),
                ('win_percentage', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('batters_faced', models.IntegerField(default=0)),
                ('innings_pitched', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('hits', models.IntegerField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
                ('bases_on_balls', models.IntegerField(default=0)),
                ('intentional_walk', models.IntegerField(default=0)),
                ('hit_by_pitch', models.IntegerField(default=0)),
                ('strike_outs', models.IntegerField(default=0)),
                ('wild_pitches', models.IntegerField(default=0)),
                ('balks', models.IntegerField(default=0)),
                ('runs_allowed', models.IntegerField(default=0)),
                ('earned_runs_allowed', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball_player_app.Player')),
            ],
            options={
                'db_table': 'player_pitching_stats',
            },
        ),
    ]
