# Generated by Django 2.2.4 on 2019-09-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_player_app', '0007_playerpitchingstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marines', models.IntegerField(default=0)),
                ('tigers', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'test_model',
            },
        ),
    ]
